kvmd:
    atx:
        type: cmd
        # 指定状态查询和动作命令
        get_status_cmd: ["/etc/kvmd/custom_atx/gpio.sh", "status"]
        short_press_cmd: ["/etc/kvmd/custom_atx/gpio.sh", "short"]
        long_press_cmd: ["/etc/kvmd/custom_atx/gpio.sh", "long"]
        reset_press_cmd: ["/etc/kvmd/custom_atx/gpio.sh", "reset"]
        interval: 2 # 每 2 秒刷新一次状态

    gpio:
        drivers:
            # 你之前的 KVM 切换按钮依然可以保留
            input1:
                type: cmd
                cmd: [/etc/kvmd/kvm_input.sh, 1]
            input2:
                type: cmd
                cmd: [/etc/kvmd/kvm_input.sh, 2]
        scheme:
            input1-button:
                driver: input1
                pin: 0
                mode: output
                switch: false
            input2-button:
                driver: input2
                pin: 0
                mode: output
                switch: false
        view:
            header:
                title: "高级功能"
            table:
                - ["#电源状态"]
                - ["主机电源:", ATX_STATUS] # 自动显示 get_status_cmd 的结果
                - ["#电源操作"]
                - ["短按电源:", ATX_SHORT]
                - ["长按强制关机:", ATX_LONG]
                - ["重启主机:", ATX_RESET]
                - []
                - ["#KVM 切换"]
                - ["HDMI 1", input1-button|切换]
                - ["HDMI 2", input2-button|切换]


vnc:
    keymap: /usr/share/kvmd/keymaps/en-us
    mouse_output: usb

    auth:
        vncauth:
            enabled: true

    memsink:
        jpeg:
            sink: "kvmd::ustreamer::jpeg"
        h264:
            sink: "kvmd::ustreamer::h264"

media:
    memsink:
        h264:
            sink: 'kvmd::ustreamer::h264'

        jpeg:
            sink: 'kvmd::ustreamer::jpeg'

otgnet:
    commands:
        post_start_cmd:
            - "/bin/true"
        pre_stop_cmd:
            - "/bin/true"
        sysctl_cmd:
            #- "/usr/sbin/sysctl"
            - "/bin/true"

nginx:
    http:
        port: 8080
    https:
        port: 4430
